### ISSUE TITLE
Using MS Sql as data store

### ISSUE THREAD

**Issue by MehranDHN** [KalikoCMS/DemoSite.Mvc#13]
I can't manage to use SqlExpress as project data store even after adding KalikoCMS.Data.SqlServer to project and setting proper Connection string in Web Config.
![image](https://user-images.githubusercontent.com/9722881/71555028-29729180-2a3c-11ea-9bbd-89f3d2274dda.png)

**Comment by MehranDHN** [comment]
Probably this error is because of something wrong in Telerik OpenAccess ORM configuraion which is deprecated and  unfortunately I don't have any experiences using it. Frankly i hate it,
Kaliko documentation says choosing different data store including MS SQL/SqlExpress is easy just by setting proper connection string and adding KalikoCMS.Data.SqlServer nuget package but It seems it's not.

**Comment by fschultz** [comment]
Hi,
I haven't seen this error before when running against SQL Server Express instances.

What version of SQL Server Express are you running? And how are you addressing the instance in your connection string (data source)?

It could as you say be related to the Telerik OpenAccess ORM (which will be replaced by EF Core in future versions) but the error message could indicate something wrong in the connection string (for instance double \\\\ instead of \\).

**Comment by MehranDHN** [comment]
Thank you for quick response.
This is my connection string to Sql Express 2014 instance
`
  <connectionStrings>
    <add name="KalikoCMS" connectionString="Data Source=.\\SqlExpress2k4;initial catalog=CMSDB;user id=sa;password=mysecretpassword;" providerName="System.Data.SqlClient" />    
  </connectionStrings>
`

**Comment by MehranDHN** [comment]
This is true using double \\ makes trouble .

**Comment by fschultz** [comment]
Great to hear that you've located the problem. Just wanted to check in to hear if you got everything else up and running?

**Comment by MehranDHN** [comment]
Thank you again . Yes The project is up and running.
I really like the way you design the project in the core specially flexible property types to exchange data between Views and Controllers. Hope to use the next version.
